<a href="https://colab.research.google.com/github/sopkart/ai-workshop-summer-2022/blob/main/FromScratch_Perceptron_%26_Linear_Reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

def readDataFile(fileName):
  return pd.read_csv(fileName, names=['x1', 'x2', 'x3', 'x4', 'y'])

In [ ]:
from sklearn.model_selection import train_test_split
def splitData(data, t_size):
  return train_test_split(data, test_size=t_size, random_state=50)


In [ ]:
def get_X_Y(data):
  return data.loc[:,'x1':'x4'].values, data.loc[:, 'y'].values

In [ ]:
'''
x = [x1 x2 x3 x4]
w = [w1 w2 w3 w4]
b = c

Ex: for single column_or_1d
    x = [a]
    w = [b]
    b = c

    w * b = ab
    y = w * x + b // simple mathematical operation

For multiple columns of x, where no of columns > 1
  x = [x1 x2 x3 x4]
  w = [w1 w2 w3 w4]
  b = c

  x and w are vectors
   x * w = (x1.w1 + x2.w2 + x3.w3 + x4.w4)

  Since x and w are represent as row matrix(if any doubt, google about 'row matrix')
    we have to take
      xT * w

'''
# h(x)
def _hypo(X, w, b):
  return np.dot(X, w) + b

# loss(x)
def _loss(X, Y, w, b):
  loss = (-Y * _hypo(X, w, b))
  loss[loss >= 0] = 1
  loss[loss < 0] = 0
  return loss

''' intial w, b
      w(t+1) = w(t) - stepSize * delta_w(t)
      b(t+1) = b(t) - stepSize * delta_b(t)
   until min is found or loss == 0
'''
#gradient_descent()
def gradientDescent(X, Y, w0, b0, stepSize):
  #intial w0, b0
  w_t = w0
  b_t = b0
  it = 1

  loss = _loss(X, Y, w_t, b_t)
  no_of_misc = sum(loss)
  while (no_of_misc != 0):

    delta_b = Y * loss
    delta_w = np.sum(delta_b[:, np.newaxis] * X, axis=0)

    w_t += stepSize * delta_w
    b_t += stepSize * sum(delta_b)

    loss = _loss(X, Y, w_t, b_t)
    no_of_misc = sum(_loss(X, Y, w_t, b_t))

    it +=1 
  return w_t, b_t, it


In [ ]:
data = readDataFile('perceptron.data')
tr_data, tst_data = splitData(data, 0.05)

X, Y = get_X_Y(tr_data)

w, b, it = gradientDescent(X, Y, [1, 1, 1, 1], 1, 0.1)

print(w)
print(b)

print("No of iteration: ", it)

Xt, Yt = get_X_Y(tst_data)
ls = _loss(Xt, Yt, w, b)
print("Accurancy :", 1 - (sum(ls)/ls.shape[0]))

[ 44.33989613  15.10542273   0.17524539 -50.88189332]
-97.00000000000001
No of iteration:  36
Accurancy : 1.0


In [ ]:
w, b, it = gradientDescent(X, Y, [0, 0, 0, 0], 0, 0.1)

print(w)
print(b)

print("No of iteration: ", it)
Xt, Yt = get_X_Y(tst_data)
ls = _loss(Xt, Yt, w, b)
print("Accurancy :", 1 - (sum(ls)/ls.shape[0]))

[ 64.97172593  22.67096543   0.75327918 -75.49946545]
-142.10000000000005
No of iteration:  30
Accurancy : 1.0


In [ ]:
w, b, it = gradientDescent(X, Y, [0, 0, 0, 0], 0, 1)

print(w)
print(b)

print("No of iteration: ", it)


Xt, Yt = get_X_Y(tst_data)
ls = _loss(Xt, Yt, w, b)
print("Accurancy :", 1 - (sum(ls)/ls.shape[0]))

[ 649.71725933  226.70965427    7.53279184 -754.99465449]
-1421.0
No of iteration:  30
Accurancy : 1.0


In [ ]:
# h(x)
def _hypo(X, w, b):
  return np.dot(X, w) + b

# loss(x)
def _loss(X, Y, w, b):
  return np.sum(((_hypo(X, w, b) - Y) ** 2)/ (2 * X.shape[0]))

''' intial w, b
      w(t+1) = w(t) - stepSize * delta_w(t)
      b(t+1) = b(t) - stepSize * delta_b(t)
   until convergence or gradient is very small
'''
#gradient_descent()
def gradientDescent(X, Y, w0, b0, stepSize):
  m = X.shape[0]
  w_t = w0
  b_t = b0
  it = 1

  while (it < 10000):
    ploss = _loss(X, Y, w_t, b_t)
    
    delta_b = np.sum(_hypo(X, w_t, b_t) - Y) / m
    delta_w = np.sum(X * (_hypo(X, w_t, b_t) - Y).reshape(-1, 1), axis =0) / m

    w_t -= stepSize * delta_w
    b_t -= stepSize * delta_b

    loss = _loss(X, Y, w_t, b_t)
    
    if (abs(ploss-loss) < 10**(-9)):
      break

    it +=1 
  return w_t, b_t, it

In [ ]:
from sklearn import datasets, linear_model, metrics

boston = datasets.load_boston(return_X_y=False)
  
# defining feature matrix(X) and response vector(y)
X = boston.data
y = boston.target

w_t = np.ones(X.shape[1])
b_t = 1


#np.dot(X, w) + b

w, b, it = gradientDescent(X, y, np.zeros(X.shape[1]), 0, 1)